/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_AudioStream */

#ifndef _Included_org_lecturestudio_avdev_AudioStream
#define _Included_org_lecturestudio_avdev_AudioStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    attachSessionListener
 * Signature: (Lorg/lecturestudio/avdev/AudioSessionListener;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_AudioStream_attachSessionListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    detachSessionListener
 * Signature: (Lorg/lecturestudio/avdev/AudioSessionListener;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_AudioStream_detachSessionListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    getVolume
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_lecturestudio_avdev_AudioStream_getVolume
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    setVolume
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_AudioStream_setVolume
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    getMute
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_lecturestudio_avdev_AudioStream_getMute
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    setMute
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_AudioStream_setMute
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    setAudioFormat
 * Signature: (Lorg/lecturestudio/avdev/AudioFormat;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_AudioStream_setAudioFormat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    getAudioFormat
 * Signature: ()Lorg/lecturestudio/avdev/AudioFormat;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_AudioStream_getAudioFormat
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    setBufferLatency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_AudioStream_setBufferLatency
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    getBufferLatency
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lecturestudio_avdev_AudioStream_getBufferLatency
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioStream
 * Method:    getStreamPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_lecturestudio_avdev_AudioStream_getStreamPosition
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
