/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_DeviceManager */

#ifndef _Included_org_lecturestudio_avdev_DeviceManager
#define _Included_org_lecturestudio_avdev_DeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_DeviceManager
 * Method:    attachHotplugListener
 * Signature: (Lorg/lecturestudio/avdev/HotplugListener;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_DeviceManager_attachHotplugListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_DeviceManager
 * Method:    detachHotplugListener
 * Signature: (Lorg/lecturestudio/avdev/HotplugListener;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_DeviceManager_detachHotplugListener
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
