/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_VideoDeviceManager */

#ifndef _Included_org_lecturestudio_avdev_VideoDeviceManager
#define _Included_org_lecturestudio_avdev_VideoDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_VideoDeviceManager
 * Method:    getDefaultVideoCaptureDevice
 * Signature: ()Lorg/lecturestudio/avdev/VideoCaptureDevice;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoDeviceManager_getDefaultVideoCaptureDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoDeviceManager
 * Method:    getVideoCaptureDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoDeviceManager_getVideoCaptureDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
