/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_VideoCaptureDevice */

#ifndef _Included_org_lecturestudio_avdev_VideoCaptureDevice
#define _Included_org_lecturestudio_avdev_VideoCaptureDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    createOutputStream
 * Signature: (Lorg/lecturestudio/avdev/VideoSink;)Lorg/lecturestudio/avdev/VideoOutputStream;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_createOutputStream
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getPictureFormats
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getPictureFormats
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getPictureControls
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getPictureControls
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getCameraControls
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getCameraControls
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    setPictureControlAutoMode
 * Signature: (Lorg/lecturestudio/avdev/PictureControlType;Z)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_setPictureControlAutoMode
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getPictureControlAutoMode
 * Signature: (Lorg/lecturestudio/avdev/PictureControlType;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getPictureControlAutoMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    setPictureControlValue
 * Signature: (Lorg/lecturestudio/avdev/PictureControlType;J)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_setPictureControlValue
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getPictureControlValue
 * Signature: (Lorg/lecturestudio/avdev/PictureControlType;)J
 */
JNIEXPORT jlong JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getPictureControlValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    setCameraControlAutoMode
 * Signature: (Lorg/lecturestudio/avdev/CameraControlType;Z)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_setCameraControlAutoMode
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getCameraControlAutoMode
 * Signature: (Lorg/lecturestudio/avdev/CameraControlType;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getCameraControlAutoMode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    setCameraControlValue
 * Signature: (Lorg/lecturestudio/avdev/CameraControlType;J)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_setCameraControlValue
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getCameraControlValue
 * Signature: (Lorg/lecturestudio/avdev/CameraControlType;)J
 */
JNIEXPORT jlong JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getCameraControlValue
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    setFrameRate
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_setFrameRate
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getFrameRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getFrameRate
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    setPictureFormat
 * Signature: (Lorg/lecturestudio/avdev/PictureFormat;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_setPictureFormat
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoCaptureDevice
 * Method:    getPictureFormat
 * Signature: ()Lorg/lecturestudio/avdev/PictureFormat;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoCaptureDevice_getPictureFormat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
