/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_Stream */

#ifndef _Included_org_lecturestudio_avdev_Stream
#define _Included_org_lecturestudio_avdev_Stream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_Stream
 * Method:    open
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_Stream_open
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_Stream
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_Stream_close
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_Stream
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_Stream_start
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_Stream
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_Stream_stop
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_Stream
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_Stream_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_Stream
 * Method:    attachStreamListener
 * Signature: (Lorg/lecturestudio/avdev/StreamListener;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_Stream_attachStreamListener
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_lecturestudio_avdev_Stream
 * Method:    detachStreamListener
 * Signature: (Lorg/lecturestudio/avdev/StreamListener;)V
 */
JNIEXPORT void JNICALL Java_org_lecturestudio_avdev_Stream_detachStreamListener
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
