/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_VideoStream */

#ifndef _Included_org_lecturestudio_avdev_VideoStream
#define _Included_org_lecturestudio_avdev_VideoStream
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_VideoStream
 * Method:    getFrameRate
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_lecturestudio_avdev_VideoStream_getFrameRate
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_VideoStream
 * Method:    getPictureFormat
 * Signature: ()Lorg/lecturestudio/avdev/PictureFormat;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_VideoStream_getPictureFormat
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
