/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_AudioDeviceManager */

#ifndef _Included_org_lecturestudio_avdev_AudioDeviceManager
#define _Included_org_lecturestudio_avdev_AudioDeviceManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_AudioDeviceManager
 * Method:    getDefaultAudioCaptureDevice
 * Signature: ()Lorg/lecturestudio/avdev/AudioCaptureDevice;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_AudioDeviceManager_getDefaultAudioCaptureDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioDeviceManager
 * Method:    getDefaultAudioPlaybackDevice
 * Signature: ()Lorg/lecturestudio/avdev/AudioPlaybackDevice;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_AudioDeviceManager_getDefaultAudioPlaybackDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioDeviceManager
 * Method:    getAudioCaptureDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_AudioDeviceManager_getAudioCaptureDevices
  (JNIEnv *, jobject);

/*
 * Class:     org_lecturestudio_avdev_AudioDeviceManager
 * Method:    getAudioPlaybackDevices
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_AudioDeviceManager_getAudioPlaybackDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
