/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_AudioPlaybackDevice */

#ifndef _Included_org_lecturestudio_avdev_AudioPlaybackDevice
#define _Included_org_lecturestudio_avdev_AudioPlaybackDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_AudioPlaybackDevice
 * Method:    createInputStream
 * Signature: (Lorg/lecturestudio/avdev/AudioSource;)Lorg/lecturestudio/avdev/AudioInputStream;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_AudioPlaybackDevice_createInputStream
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
