/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lecturestudio_avdev_AudioCaptureDevice */

#ifndef _Included_org_lecturestudio_avdev_AudioCaptureDevice
#define _Included_org_lecturestudio_avdev_AudioCaptureDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lecturestudio_avdev_AudioCaptureDevice
 * Method:    createOutputStream
 * Signature: (Lorg/lecturestudio/avdev/AudioSink;)Lorg/lecturestudio/avdev/AudioOutputStream;
 */
JNIEXPORT jobject JNICALL Java_org_lecturestudio_avdev_AudioCaptureDevice_createOutputStream
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
